apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-db-secure
provisioner: kubernetes.io/portworx-volume
parameter:
  fs: "xfs"
  block_size: "32"
  repl: "2"
  snap_interval: "30"
  io-priority: "medium"
  secure: "true"